name = "benchmark"
version = "1.0.0"
maintainer = "David Pfister"
author = "David Pfister"
description = "benchmarking framework"
categories = ["benchmark"]
keywords = ["benchmark", "timer"]
homepage = "https://github.com/davidpfister/benchmark.f"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
external-modules = ["omp_lib","symengine"]

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[library]
source-dir = "src"
include-dir = ["include"]

[fortran]
implicit-external = true

[install]
library = false

[[example]]
name = "simple"
source-dir = "examples/simple"
main = "Simple.f90"

[[example]]
name = "poisson"
source-dir = "examples/poisson"
main = "Poisson.f90"

[[example]]
name = "allocation"
source-dir = "examples/allocation"
main = "Allocation.f90"

[[example]]
name = "uppercasing"
source-dir = "examples/uppercasing"
main = "UpperCasing.f90"

[[example]]
name = "parsers"
source-dir = "examples/parsers"
main = "Parsers.f90"
[example.dependencies]
equationparser = {path = "./examples/parsers/equationparser"}
evaluate = {path = "./examples/parsers/evaluate"}
FEQParse = {path = "./examples/parsers/feq-parse"}
function_parser = {path = "./examples/parsers/fortran_function_parser"}
interpreter = {path = "./examples/parsers/fortran_parser"}
fortranparser = {path = "./examples/parsers/FortranParser"}
fparser = {path = "./examples/parsers/fparser"}
fee = {path = "./examples/parsers/FunctionParser"}
M_calculator = {path = "./examples/parsers/M_calculator"}
# symengine = {path = "./examples/parsers/symengine"}

[[test]]
name = "test"
source-dir = "tests"
main="main.f90"